import type { RepoFileMeta, ScanStats } from "../app/app-types";
import { detectEntryPoints } from "./context-quality";
import { dirNameOf } from "./file-path";

export interface AgentsMdOptions {
  projectName?: string;
}

interface DirSummary {
  path: string;
  fileCount: number;
}

function topLevelDirectories(files: RepoFileMeta[]): DirSummary[] {
  const counts = new Map<string, number>();
  for (const file of files) {
    const top = file.dirPath.split("/").filter(Boolean)[0];
    if (!top) continue;
    counts.set(top, (counts.get(top) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([path, fileCount]) => ({ path, fileCount }))
    .sort((a, b) => b.fileCount - a.fileCount)
    .slice(0, 10);
}

/**
 * Generates a draft AGENTS.md/CLAUDE.md from a repository scan already done
 * by the forge worker. Template-based, not LLM-based, on purpose: every line
 * traces back to a file that's actually in the scan, and every TODO marks a
 * fact this scan genuinely can't infer -- consistent with ContextForge never
 * sending repository content anywhere.
 */
export function generateAgentsMd(stats: ScanStats, files: RepoFileMeta[], options: AgentsMdOptions = {}): string {
  const includedFiles = files.filter((file) => file.included);
  const languages = [...stats.languages].sort((a, b) => b.bytes - a.bytes);
  const entryPoints = detectEntryPoints(files);
  const testDirs = [...new Set(includedFiles.filter((file) => file.isTest).map((file) => dirNameOf(file.path)))].slice(
    0,
    5,
  );
  const configFiles = includedFiles
    .filter((file) => file.isConfig)
    .map((file) => file.path)
    .slice(0, 10);
  const topDirs = topLevelDirectories(includedFiles);

  const name = options.projectName?.trim() || "this project";
  const lines: string[] = [];

  lines.push(`# Agent instructions for ${name}`);
  lines.push("");
  lines.push(
    "_Draft generated by ContextForge from a repository scan -- detected facts only. Review and fill in every TODO before committing this file; nothing here is invented._",
  );
  lines.push("");

  lines.push("## Stack");
  lines.push("");
  if (languages.length > 0) {
    lines.push("Detected languages, by included source volume:");
    lines.push("");
    for (const lang of languages.slice(0, 6)) {
      lines.push(`- **${lang.language}** -- ${lang.files} file${lang.files === 1 ? "" : "s"}`);
    }
  } else {
    lines.push("TODO: no languages detected from the current scan.");
  }
  lines.push("");

  lines.push("## Entry points");
  lines.push("");
  if (entryPoints.length > 0) {
    for (const entry of entryPoints.slice(0, 8)) lines.push(`- \`${entry.path}\``);
  } else {
    lines.push("TODO: no entry point auto-detected -- add the file(s) where execution starts.");
  }
  lines.push("");

  lines.push("## Project layout");
  lines.push("");
  if (topDirs.length > 0) {
    for (const dir of topDirs) {
      lines.push(`- \`${dir.path}/\` -- ${dir.fileCount} file${dir.fileCount === 1 ? "" : "s"} -- TODO: describe what lives here`);
    }
  } else {
    lines.push("TODO: describe the top-level layout.");
  }
  lines.push("");

  lines.push("## Conventions");
  lines.push("");
  lines.push("TODO: naming conventions, code style, patterns to follow or avoid.");
  lines.push("");

  lines.push("## Testing");
  lines.push("");
  if (testDirs.length > 0) {
    lines.push("Detected test locations:");
    lines.push("");
    for (const dir of testDirs) lines.push(`- \`${dir || "(root)"}\``);
    lines.push("");
    lines.push("TODO: how to run tests, and what must pass before a change is considered done.");
  } else {
    lines.push("TODO: no test directory detected -- describe how this project is tested, if at all.");
  }
  lines.push("");

  lines.push("## Config & build");
  lines.push("");
  if (configFiles.length > 0) {
    for (const file of configFiles) lines.push(`- \`${file}\``);
  } else {
    lines.push("TODO: no config files detected in the current scan.");
  }
  lines.push("");

  lines.push("## Deployment");
  lines.push("");
  lines.push("TODO: how and where this ships.");
  lines.push("");

  return lines.join("\n");
}
